services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: kani
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
      - spring
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring

  customer:
    image: arnaudkaninda/customer:latest
    container_name: customer
    ports:
      - "8090:8090"
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - postgres
      - rabbitmq
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  fraud:
    image: arnaudkaninda/fraud:latest
    container_name: fraud
    ports:
      - "8091:8091"
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - postgres
      - rabbitmq
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  notification:
    image: arnaudkaninda/notification:latest
    container_name: notification
    ports:
      - "8092:8092"
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - postgres
      - rabbitmq
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  rabbitmq:
    image: rabbitmq:3.9.16-management-alpine
    container_name: rabbitmq
    networks:
      - spring
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres:
  pgadmin: