
server:
  port: 8093
spring:
  application:
    name: gateway
  zipkin:
    base-url: http://127.0.0.1:9411/
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/customers/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true